### ISSUE TITLE
Using hash or UUID instead of database ID

### ISSUE THREAD

**Issue by SachinGanesh** [laravel-orion/laravel-orion#1]
Thank you for this wonderful package. I want to use [Hashids](https://github.com/vinkla/laravel-hashids) instead of DB id's. How this can be integrated with your package?

**Comment by alexzarbn** [comment]
Hi @SachinGanesh,

Glad you found it useful 🙂

I believe Hashids should be implemented on the model level. Take a look at how UUIDs are implemented in [laravel-eloquent-uuid](https://github.com/goldspecdigital/laravel-eloquent-uuid) package.
As long as it still uses default Laravel's `->save`, `->delete`, etc. methods on a model, it should work fine.

**Comment by SachinGanesh** [comment]
Yes, But I do not want to expose the DB id to the public. How the URLs is handled in the current package?

for example, Hashid's URL will be `https://myapp.com/api/users/ASCE12A34` instead of `https://myapp.com/api/users/1`

Also, in the batch update, restore etc, the plain DB id should be changed to hashid's
```
// (PATCH) https://myapp.com/api/posts/batch
{
    "resources" : {
        "ASCE12A34" : {
            "title" : "My Post 1 (updated)",
            "body" : "Example updated body text"
        },
        "ABCEX2E3Z": {
            "title" : "My Post 2",
            "body" : "Example body text"
        }
    }
}
````

Let me know if this can be achieved.

**Comment by alexzarbn** [comment]
@SachinGanesh,

If you always would like to use hashed ids to work with models (even when you call something like `->find()` outside of the API, in a repository, for example), then implementing that on model level is the way to go - Laravel Orion understands what field is used for model keys and whether it is an int or a string - does not matter.

However, if you would like to use hashed ids only on API level, but still access models using normal DB ids, then it is not currently possible. I will look into providing the ability to customize that behaviour somewhere closer to the stable release.

**Comment by alexzarbn** [comment]
Hi @SachinGanesh,

It is now possible to customize how Eloquent queries are build and executed for each endpoint.
Documentation is available for [model](https://laravel-orion.github.io/docs/guide/models.html#customizing-queries) and [relation](https://laravel-orion.github.io/docs/guide/relationships.html#customizing-queries) controllers.
