### ISSUE TITLE
How to override the default api guard

### ISSUE THREAD

**Issue by gech4me** [laravel-orion/laravel-orion#2]
### Anyone who want to use web guard instead of API. 
Add the following trait on your controller, It will override the default API guard.

```
trait UserResolverTrait
{
    public function resolveUser(): ?\Illuminate\Contracts\Auth\Authenticatable
    {
        return Auth::guard('web')->user();
    }
}

```

**Comment by alexzarbn** [comment]
Hi @gech4me,

To customize how user is resolved you can now override the `resolveUser` method on a controller.
[Documentation](https://laravel-orion.github.io/docs/guide/security.html#resolving-user) has been updated with the relevant information.
