### ISSUE TITLE
Modify model query builder

### ISSUE THREAD

**Issue by SachinGanesh** [laravel-orion/laravel-orion#5]
I want to modify the model query in a controller before a request is executed. This is required if I want to filter the data and show only owned models by a user in the index method, 

Currently, I'm overriding **newModelQuery** in the controller to achieve the above

```php
//in PostController.php

public function newModelQuery(): Builder
{
    $query = $this->getModel()::query();
    if(auth()->user()->hasRole('user')){
        $query = $query->where('user_id', auth()->user()->id);
    }
    return $query;
}
```

is there any better way to do this?

Can the hook itself pass the query builder as shown below?
```php
protected function beforeIndex(Request $request, $query)
{
    if(auth()->user()->hasRole('user')){
        $query = $query->where('user_id', auth()->user()->id);
    }
}
```

**Comment by alexzarbn** [comment]
Hi @SachinGanesh,

I think the proposed improvement makes sense 🤔
Same would be possible for `beforeShow`, `beforeUpdate`, `beforeDestroy`, and `beforeRestore` hooks as well - query builder would be passed alongside the resource key.
Gonna make the necessary changes over the weekend.

However, If you would like to apply the role filter to all endpoints (not just the index one), current approach is correct.

**Comment by SachinGanesh** [comment]
Okay. Thank you!

**Comment by alexzarbn** [comment]
@SachinGanesh,

Went for a bit different approach, but the end result is basically the same.

There are now "wrapper methods": `buildIndexQuery`, `buildShowQuery`,  `buildUpdateQuery`, `buildDestroyQuery`, and `buildRestoreQuery` that you can override in your model controller and customize the query used to fetch model(s) in the given method/endpoint.
Documentation and wrapper methods in relation controllers is coming next week ~

In your case, the solution for index endpoint would be:
```php
//in PostController.php

protected function buildIndexQuery(Request $request, array $requestedRelations): Builder
{
    $query = parent::buildIndexQuery($request, $requestedRelations);

    if(auth()->user()->hasRole('user')){
        $query = $query->where('user_id', auth()->user()->id);
    }
        
    return $query;
}
```

**Comment by SachinGanesh** [comment]
@alexzarbn This approach looks good to me. Thank you!
