### ISSUE TITLE
How to disable same routes?

### ISSUE THREAD

**Issue by xnf4o** [laravel-orion/laravel-orion#7]
As example i had to disable any BATCH routes for some reason. How can i make this?

**Comment by alexzarbn** [comment]
Hi @xnf4o,

When you register a route, it returns an instance of Laravel's `PendingResourceRegistration` class.
You can use `->except` method to disable specific routes.

In your case:

```php
Orion::resource('posts', 'API\PostsController')->except(['batchStore', 'batchUpdate', 'batchDestroy']);
```

However, I will look into providing an additional method (something like `->withoutBatchOperations()` that would disable all batch routes at once.

**Comment by alexzarbn** [comment]
It is now possible to disable all batch routes at once using `->withoutBatch` method on a resource.
[Documentation](https://laravel-orion.github.io/docs/guide/batch-operations.html#disabling-batch-operations) has been updated with relevant information.
