### ISSUE TITLE
How to validate the parameter passed in the path uri?

### ISSUE THREAD

**Issue by davigs** [laravel-orion/laravel-orion#9]
Hello guys, I need to validate the parameter passed in the path.
The route is defined as follows:
`api/customers/{customer}/address`

In the validation rules the variable `$this->request->customer` is null.

![Captura de Tela 2020-10-12 às 07 25 54](https://user-images.githubusercontent.com/4110873/95736122-30c9fb00-0c5c-11eb-983c-8311fc921108.png)

And that is the request for the API.

![Captura de Tela 2020-10-12 às 07 28 14](https://user-images.githubusercontent.com/4110873/95736359-83a3b280-0c5c-11eb-9d66-3cbd96ce7e98.png)

**Comment by alexzarbn** [comment]
Hi @davigs,

Usually route parameters are not meant to be validated via Request classes - it should be accomplished by utilizing [route parameters regular expression constraints](https://laravel.com/docs/5.8/routing#parameters-regular-expression-constraints), [route model binding](https://laravel.com/docs/5.8/routing#parameters-regular-expression-constraints) or logic in a specific controller. 

However, there is a [topic](https://laracasts.com/discuss/channels/general-discussion/how-to-validate-route-parameters-in-laravel-5?page=1#reply=158222) on Laracasts forum that provides a workaround for making route parameters validation work via Request classes.

I hope that helps ~
